"""Canonical filenames for station-scoped New Releases data."""

from __future__ import annotations


NEW_RELEASES_PLAYLIST_NAME = "New Releases"
NEW_RELEASES_PLAYLIST_FILENAME = f"{NEW_RELEASES_PLAYLIST_NAME}.csv"
NEW_RELEASES_METADATA_FILENAME = f"{NEW_RELEASES_PLAYLIST_NAME}.metadata.json"
NEW_RELEASES_ARTIST_CACHE_FILENAME = "ArtistIDs.json"
NEW_RELEASES_EXCLUSIONS_FILENAME = f"{NEW_RELEASES_PLAYLIST_NAME}.exclusions.json"


__all__ = [
    "NEW_RELEASES_ARTIST_CACHE_FILENAME",
    "NEW_RELEASES_EXCLUSIONS_FILENAME",
    "NEW_RELEASES_METADATA_FILENAME",
    "NEW_RELEASES_PLAYLIST_FILENAME",
    "NEW_RELEASES_PLAYLIST_NAME",
]
